server:
  port: 8888

  #spring
spring:
  thymeleaf:
    cache: false
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sans_security?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 123456

  #mybatis
#mybatis:
 # type-aliases-package: com/demo/pojo
 # config-location: classpath:mybatis/mybatis-config.xml
 # mapper-locations: classpath*:mybatis/mapper/*.xml

mybatis-plus:
  type-aliases-package: com/demo/pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath*:mybatis/mapper/*.xml

#日志输出配置
logging:
  file:
    path: ../logs
  level:
   com.demo.mapper: debug
   root: debug





